# Generated by Django 4.2.1 on 2024-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.IntegerField(max_length=10)),
                ('psw', models.CharField(max_length=10)),
                ('cpsw', models.CharField(max_length=20)),
            ],
        ),
    ]
