# Generated by Django 4.2.1 on 2024-01-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_regimodel_phn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regimodel',
            name='cpsw',
        ),
    ]
