# Generated by Django 4.2.1 on 2024-01-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='descrpt',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='prodname',
            field=models.CharField(max_length=50),
        ),
    ]
