# Generated by Django 5.0.1 on 2024-01-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_productmodel1_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='date',
        ),
    ]
