# Generated by Django 5.0.1 on 2024-01-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_remove_productmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('wishid', models.IntegerField()),
                ('itemname', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='ecom/static')),
                ('price', models.IntegerField()),
                ('descript', models.CharField(max_length=500)),
                ('prodid1', models.IntegerField()),
            ],
        ),
    ]
