# Generated by Django 5.0.1 on 2024-01-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('phn', models.IntegerField()),
                ('zip', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('branme', models.CharField(max_length=100)),
                ('acname', models.CharField(max_length=50)),
                ('acno', models.IntegerField()),
                ('expdte', models.DateField()),
            ],
        ),
    ]
