# Generated by Django 5.0.1 on 2024-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofrmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='ecom/static')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
