# Generated by Django 5.0.1 on 2024-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_reviewmodel_imag'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expdte', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='acname',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='acno',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='bname',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='branme',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='expdte',
        ),
    ]
